import os
import sys
import json
from github import Github, GithubException

def load_event():
    """Load GitHub event JSON from env var."""
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if not event_path or not os.path.exists(event_path):
        print("[auto_responder] No event file found; aborting.")
        sys.exit(0)
    try:
        with open(event_path, "r", encoding="utf-8") as f:
            event = json.load(f)
        return event
    except Exception as e:
        print(f"[auto_responder] Failed to load event JSON: {e}")
        sys.exit(1)

def get_issue_pr_info(event):
    """Extract info and context from event (supports issues/pull_request triggers)."""
    context = {"number": None, "title": "", "body": "", "url": "", "type": "", "labels": []}
    if "issue" in event:
        obj = event["issue"]
        context.update(dict(
            number=obj.get("number"),
            title=obj.get("title", ""),
            body=obj.get("body", ""),
            url=obj.get("url", ""),
            type="issue",
            labels=[lbl.get("name", "") for lbl in obj.get("labels", [])]
        ))
    elif "pull_request" in event:
        obj = event["pull_request"]
        context.update(dict(
            number=obj.get("number"),
            title=obj.get("title", ""),
            body=obj.get("body", ""),
            url=obj.get("issue_url", obj.get("url", "")),
            type="pull_request",
            labels=[lbl.get("name", "") for lbl in obj.get("labels", [])]
        ))
    return context

def should_trigger(title, body, labels=None):
    """Decide if agent should respond (customize logic here or load from file)."""
    keywords = ["EP-Signal", "W3Lgu", "MPCP"]
    try:
        if os.path.exists("agent_keywords.json"):
            with open("agent_keywords.json") as f:
                keywords += json.load(f)
    except Exception:
        pass
    checktxt = (title or "") + " " + (body or "")
    labels = labels or []
    text_in_labels = any(word in labels for word in keywords)
    return any(word in checktxt for word in keywords) or text_in_labels

def generate_checklist(body):
    """สร้าง checklist auto จาก bullet ใน issue body (หรือ custom logic อื่น)"""
    lines = [l.strip("- ").strip() for l in (body or "").split('\n') if l.strip().startswith('- ')]
    if not lines:
        return ""
    checklist = "\n".join(f"- [ ] {l}" for l in lines)
    return "### 🚦 Checklist generated by bot\n" + checklist

def agent_comment_body(lang="en"):
    if lang == "th":
        return (
            "🤖 สวัสดีจาก W3Agent! งานนี้เกี่ยวข้องกับโมดูลของระบบ W3\n"
            "Agent จะช่วยบริหารขั้นตอนถัดไปให้อัตโนมัติ\n"
            "— _W3 Auto-responder_"
        )
    return (
        "🤖 Hello from **W3Agent**!\n"
        "This issue/pull request relates to W3 system modules.\n"
        "Automated agent has picked up your topic and will help orchestrate the next steps.\n"
        "— _W3 Auto-responder_"
    )

def main():
    print("[auto_responder] Started.")
    event = load_event()
    info = get_issue_pr_info(event)
    if not info["number"]:
        print("[auto_responder] No issue or PR context found in event.")
        sys.exit(0)

    print(f"[auto_responder] Context: type={info['type']} number={info['number']} title='{info['title']}'")
    if should_trigger(info["title"], info["body"], info.get("labels")):
        github_token = os.environ.get("GITHUB_TOKEN")
        repo_name = os.environ.get("GITHUB_REPOSITORY")
        if not github_token or not repo_name:
            print("[auto_responder] Missing GITHUB_TOKEN or GITHUB_REPOSITORY; aborting.")
            sys.exit(1)
        try:
            gh = Github(github_token)
            repo = gh.get_repo(repo_name)
            issue = repo.get_issue(number=info["number"])
            comment = agent_comment_body("en")  # เปลี่ยนเป็น "th" ได้ถ้าอยาก auto ภาษาไทย
            checklist = generate_checklist(info["body"])
            if checklist:
                comment += "\n\n" + checklist
            issue.create_comment(comment)
            print(f"[auto_responder] Commented on: {info['type']} #{info['number']}")
        except GithubException as err:
            print(f"[auto_responder] GithubException: {err}")
            sys.exit(1)
        except Exception as e:
            print(f"[auto_responder] ERROR: {e}")
            sys.exit(1)
    else:
        print("[auto_responder] No relevant keywords found; no action taken.")

if __name__ == "__main__":
    main()
