"""IGET Execution Worker for W3Agent.

- รับงานที่ BBX19 "อนุมัติแล้ว" จาก approval_gate
- แปลง execution plan -> "ร่าง patch จริง" เป็นไฟล์
- เขียน patch ลง worker_output/ ให้ BBX19 วางเองผ่าน Termux
- ไม่แตะ repo จริง ไม่ commit ไม่ push (BBX19 คือคนกดวางเสมอ)

หลักการ: No AI merge / Human in loop / LINE_B / Python ล้วน รันบน Termux
"""

import json
import os
import re
from datetime import datetime, timezone
from typing import Any, Callable, Dict, List, Optional


DEFAULT_OUTPUT_DIR = "worker_output"

APPROVED_STATES = {
    "approved_by_bbx19",
    "approved_run_requested",
}


class PatchDraft:
    """patch หนึ่งชิ้นที่ worker ร่างขึ้น — ยังไม่ลง repo

    ใช้ class ธรรมดา (ไม่ใช่ @dataclass) เพื่อเลี่ยงปัญหา
    type-hint resolution บน Python 3.13 — รันได้ทุกเวอร์ชัน
    """

    def __init__(
        self,
        target_path,
        content,
        summary,
        module="unknown",
        mutation=False,
        needs_human_review=True,
    ):
        self.target_path = target_path
        self.content = content
        self.summary = summary
        self.module = module
        self.mutation = mutation
        self.needs_human_review = needs_human_review

    def filename(self):
        safe = re.sub(r"[^A-Za-z0-9_.-]", "__", self.target_path.strip("/"))
        return f"{safe}.patch.txt"


class WorkerResult:
    """ผลลัพธ์รวมของ worker หนึ่งรอบ"""

    def __init__(self, issue_number, status, drafts=None, notes=None):
        self.issue_number = issue_number
        self.status = status
        self.drafts = drafts if drafts is not None else []
        self.notes = notes if notes is not None else []
        self.created_at = datetime.now(timezone.utc).isoformat()

    def as_dict(self):
        return {
            "issue_number": self.issue_number,
            "status": self.status,
            "created_at": self.created_at,
            "draft_count": len(self.drafts),
            "drafts": [
                {
                    "target_path": d.target_path,
                    "summary": d.summary,
                    "module": d.module,
                    "mutation": d.mutation,
                    "needs_human_review": d.needs_human_review,
                    "filename": d.filename(),
                }
                for d in self.drafts
            ],
            "notes": self.notes,
            "mutation": False,
            "return_to": "IGET",
        }


PatchBuilder = Callable[[str, str, List[str]], Optional[PatchDraft]]

_BUILDERS = {}


def register_builder(module):
    """decorator ให้แต่ละโมดูลลงทะเบียนวิธีร่าง patch ของตัวเอง"""

    def wrap(fn):
        _BUILDERS[module.strip().upper()] = fn
        return fn

    return wrap


def has_builder(module):
    return module.strip().upper() in _BUILDERS


@register_builder("GENERIC")
def _generic_scaffold(issue_title, brief, plan):
    """ร่างไฟล์ scaffold กลางจาก brief — ปลอดภัย ใช้ได้กับทุกงาน"""
    target = _guess_target_path(brief) or "worker_output/DRAFT_README.md"

    plan_lines = "\n".join(f"# - {step}" for step in plan) if plan else "# (no plan steps)"

    content = (
        "# -------------------------------------------\n"
        "# DRAFT generated by IGET execution_worker\n"
        f"# Issue: {issue_title}\n"
        f"# Generated: {datetime.now(timezone.utc).isoformat()}\n"
        "# STATUS: draft - BBX19 must review before placing into repo\n"
        "# MUTATION: false\n"
        "# -------------------------------------------\n"
        "#\n"
        "# Brief:\n"
        f"# {brief or '(no brief provided)'}\n"
        "#\n"
        "# Plan:\n"
        f"{plan_lines}\n"
        "#\n"
        "# -- implementation goes below this line --\n"
        "\n"
    )

    return PatchDraft(
        target_path=target,
        content=content,
        summary=f"scaffold draft for: {issue_title[:60]}",
        module="GENERIC",
    )


def _guess_target_path(brief):
    match = re.search(r"[A-Za-z0-9_./-]+\.(py|md|json|txt|yml|yaml)", brief or "")
    return match.group(0) if match else ""


def _extract_section(body, heading):
    pattern = re.compile(
        rf"^##\s+{re.escape(heading)}\s*$\n(?P<body>.*?)(?=^##\s+|\Z)",
        re.IGNORECASE | re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(body or "")
    return match.group("body").strip() if match else ""


def _extract_module_tags(text):
    return [m.group(1) for m in re.finditer(r"@module:([A-Za-z0-9_.:-]+)", text or "")]


def run_worker(
    issue_number,
    issue_title,
    issue_body,
    approval_status,
    plan=None,
    output_dir=DEFAULT_OUTPUT_DIR,
    write_files=True,
):
    """รับงานที่อนุมัติแล้ว -> ร่าง patch -> เขียนลง output_dir"""
    result = WorkerResult(issue_number=str(issue_number), status="idle")

    if approval_status not in APPROVED_STATES:
        result.status = "blocked_not_approved"
        result.notes.append(
            f"approval_status '{approval_status}' is not in approved states; "
            "worker will not draft. BBX19 approval required first."
        )
        return result

    brief = _extract_section(issue_body, "Brief") or (issue_body or "").strip()
    modules = _extract_module_tags(issue_body)
    plan = plan if plan is not None else []

    targeted = [m.upper() for m in modules if has_builder(m.upper())]

    if not targeted:
        targeted = ["GENERIC"]
        result.notes.append(
            "no module-specific builder matched; using GENERIC scaffold. "
            f"(detected modules: {modules or 'none'})"
        )

    for module in targeted:
        builder = _BUILDERS.get(module)
        if builder is None:
            result.notes.append(f"module '{module}' has no builder; skipped")
            continue

        try:
            draft = builder(issue_title, brief, plan)
        except Exception as exc:
            result.notes.append(f"builder '{module}' raised: {exc!r}")
            continue

        if draft is None:
            result.notes.append(f"builder '{module}' produced no draft")
            continue

        result.drafts.append(draft)

    if write_files and result.drafts:
        _write_drafts(output_dir, result)

    result.status = "drafted" if result.drafts else "no_draft_produced"
    return result


def _write_drafts(output_dir, result):
    os.makedirs(output_dir, exist_ok=True)

    for draft in result.drafts:
        path = os.path.join(output_dir, draft.filename())
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(draft.content)

    summary_path = os.path.join(output_dir, f"_SUMMARY_issue_{result.issue_number}.json")
    with open(summary_path, "w", encoding="utf-8") as fh:
        json.dump(result.as_dict(), fh, ensure_ascii=False, indent=2)


def render_worker_comment(result):
    if result.status == "blocked_not_approved":
        return (
            "## IGET Execution Worker\n\n"
            f"Issue: #{result.issue_number}\n"
            "Status: `blocked_not_approved`\n\n"
            "Worker did not draft anything because BBX19 approval was not detected.\n\n"
            "RETURN_TO: `IGET`\nMUTATION: `false`\n"
        )

    if not result.drafts:
        return (
            "## IGET Execution Worker\n\n"
            f"Issue: #{result.issue_number}\n"
            f"Status: `{result.status}`\n\n"
            "Worker ran but produced no draft. See notes:\n"
            + "\n".join(f"- {n}" for n in result.notes)
            + "\n\nRETURN_TO: `IGET`\nMUTATION: `false`\n"
        )

    draft_lines = "\n".join(
        f"- `{d.filename()}` -> target: `{d.target_path}` ({d.summary})"
        for d in result.drafts
    )
    note_lines = "\n".join(f"- {n}" for n in result.notes) if result.notes else "- none"

    return (
        "## IGET Execution Worker\n\n"
        f"Issue: #{result.issue_number}\n"
        f"Status: `{result.status}`\n"
        f"Drafts produced: {len(result.drafts)}\n\n"
        "### Drafted patches (review before placing)\n"
        f"{draft_lines}\n\n"
        "### Notes\n"
        f"{note_lines}\n\n"
        "### Boundary\n"
        "- patches are DRAFTS only, written to `worker_output/`\n"
        "- repo is NOT mutated by the worker\n"
        "- BBX19 reviews and places each patch manually via Termux\n\n"
        "RETURN_TO: `IGET`\n"
        "APPROVAL_REQUIRED: `true` (for placement)\n"
        "MUTATION: `false`\n"
        "TRACE: `execution_worker`\n"
    )


__all__ = [
    "PatchDraft",
    "WorkerResult",
    "register_builder",
    "has_builder",
    "run_worker",
    "render_worker_comment",
]

